name: Android CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ master, devel ]
  schedule:
    - cron:  '30 12 * * 4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17
          cache: 'gradle'

      - name: Loading submodules
        run: git submodule update --init --recursive   

      - name: Loading secrets
        env:
          gservices: ${{ secrets.googleservices }}
          aqicnkey: ${{ secrets.aqicnapikey }}
        run: |
          echo $gservices > ./app/google-services.json
          echo $aqicnkey > ./app/src/main/res/values/api_aqicn.xml
      - name: Build the app
        run: ./gradlew build

